CREATE TABLE USUARIO(
	IDUSUARIO SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SOBRENOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	DATA_CADASTRO TIMESTAMP,
	DISPONIBILIDADE VARCHAR(15) CHECK (DISPONIBILIDADE IN ('MANHA', 'TARDE', 'NOITE','FIM_SEMANA','TOTAL_DISPONIBILIDADE')) NOT NULL,
	DESCRICAO VARCHAR(300) NOT NULL,
	LINGUAGEM VARCHAR(30) NOT NULL,
	AREA VARCHAR(50) NOT NULL
);